# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and Push Template

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      IMAGE_TAG:
        required: false
        type: string
        default: "latest"
      DOCKERFILE:
        required: false
        type: string
        default: "Dockerfile"
      DOCKERFILE_CONTEXT:
        required: false
        type: string
        default: "."
    secrets:
      DOCKERHUB_TOKEN:
        required: true
    

permissions:
  contents: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      DOCKERHUB_IMAGE_NAME: "docker.io/joaotiagoalmeid4/${{ inputs.IMAGE_NAME }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the Image
        run: |
          ./scripts/build.sh ${{ inputs.DOCKERFILE }} ${{ inputs.DOCKERFILE_CONTEXT }} ${{ env.DOCKERHUB_IMAGE_NAME }} ${{ inputs.IMAGE_TAG }}

      - name: Login in DockerHub
        run: |
          docker login --username  ${{ vars.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Push the Image
        run: |
          docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}


