name: Build and Push Template

on:
  workflow_call:
    inputs:
      IMAGE_NAME:
        required: false
        type: string
        default: ${{ github.event.repository.name }}
      IMAGE_TAG:
        required: false
        type: string
        default: "build-${{ github.sha }}"
      DOCKERFILE:
        required: false
        type: string
        default: "Dockerfile"
      DOCKERFILE_CONTEXT:
        required: false
        type: string
        default: "."
    secrets:
      DOCKERHUB_TOKEN:
        required: true
    

permissions:
  contents: read

jobs:
  build:
    name: Build and Push
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      DOCKERHUB_IMAGE_NAME: "docker.io/${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.IMAGE_NAME }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the Image
        run: | 
          docker build \
            --build-arg=${{ env.DOCKERHUB_IMAGE_NAME }} \
              -t ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ inputs.IMAGE_TAG }} \
              -f ${{ inputs.DOCKERFILE }} ${{ inputs.DOCKERFILE_CONTEXT }}

      - name: Login in DockerHub
        run: |
          docker login --username  ${{ vars.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Push the Image
        run: |
          docker push ${{ env.DOCKERHUB_IMAGE_NAME }}:${{ inputs.IMAGE_TAG }}


