name: CI Base Template

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  tag:
    needs: build
    uses: ./.github/workflows/tag.yml
    secrets: inherit

