# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Base Template

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  tag:
    needs: build
    uses: ./.github/workflows/tag.yml
    secrets: inherit

