# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Login in DockerHub 

on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        required: true
        type: string
      IMAGE_NAME:
        required: false
        default: "docker.io/joaotiagoalmeid4/github-base-templates"
        type: string
      IMAGE_TAG:
        required: false
        default: "latest"
        type: string
    secrets:
      DOCKERHUB_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  login:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
        - run: |
            docker login --username ${{ inputs.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
  
